format = """
$username $directory$fill$git_branch$git_status[ ]()$memory_usage[ ]()$time[ ]()$shell
 $character
"""

add_newline = true

scan_timeout = 50

command_timeout = 550

[character]
success_symbol = "[](fg:#50fa7b bold)"
error_symbol = "[](fg:#ff5555 bold)"

[fill]
symbol = " "
disabled = false

[time]
format = '[](fg:#bd93f9)[ \[$time\] ](fg:#282a36 bg:#bd93f9)[](fg:#bd93f9)'
utc_time_offset = "local"
time_format = "%T"
disabled = false
time_range = "-"

[git_branch]
format = "[](fg:#8be9fd)[$symbol](fg:#282a36 bg:#8be9fd)[$branch ](fg:#282a36 bg:#8be9fd)[](fg:#8be9fd)"
symbol = " "

[shell]
bash_indicator = "[](fg:#c4c431 bg:#6f6565)[BSH-MODE](fg:#fff1cf bg:#c4c431)[](fg:#c4c431 bg:#6f6565)[  ](fg:#c4c431 bg:#6f6565)[](fg:#6f6565)"
zsh_indicator = "[](fg:#94b3a8 bg:#6f6565)[ZSH-MODE](fg:#fff1cf bg:#94b3a8)[](fg:#94b3a8 bg:#6f6565)[  ](fg:#94b3a8 bg:#6f6565)[](fg:#6f6565)"
nu_indicator = "[](fg:#fe6142 bg:#6f6565)[NSH-MODE](fg:#fff1cf bg:#fe6142)[](fg:#fe6142 bg:#6f6565)[  ](fg:#fe6142 bg:#6f6565)[](fg:#6f6565)"
fish_indicator = "[](fg:#f8f8f2)[FISH](fg:#282a36 bg:#f8f8f2)[](fg:#f8f8f2)[ ]()[](fg:#bd93f9)[ ](fg:#282a36 bg:#bd93f9)[](fg:#bd93f9)"
elvish_indicator = "[](fg:#a742f5 bg:#6f6565)[ESH-MODE](fg:#fff1cf bg:#a742f5)[](fg:#a742f5 bg:#6f6565)[](fg:#bd93f9)[  ](fg:#a742f5 bg:#bd93f9)[](fg:#bd93f9)"
xonsh_indicator = "[](fg:#70ff24 bg:#6f6565)[XSH-MODE](fg:#fff1cf bg:#70ff24)[](fg:#70ff24 bg:#6f6565)[  ](fg:#70ff24 bg:#6f6565)[](fg:#6f6565)"
unknown_indicator = "[](fg:#fff1cf bg:#6f6565)[???-MODE][](fg:#6f6565)"
style = "fg:#fff1cf bg:#6f6565"
disabled = false

[directory]
format = "[](fg:#bd93f9)[$path ]($style)[$read_only](fg:#f8f8f2 bg:bd93f9)[ ](fg:#bd93f9 bold)"
style = "fg:#282a36 bg:#bd93f9"
truncation_symbol = "…/"
truncate_to_repo = false
truncation_length = 100
home_symbol = "  "

[git_status]
format = '([\[$all_status$ahead_behind\]](fg: bg:#6f6565))'

[username]
format = "[](fg:#f8f8f2 bold)[ ](fg:#282a36 bg:#f8f8f2 bold)[](fg:#f8f8f2 bold)"
show_always = true
disabled = false

[memory_usage]
disabled = false
format = "$ram_pct"
