# format = """
# $username$directory$fill$container$git_branch$git_status$memory_usage$cmd_duration$time[]()$shell
#  $character
# """
format = """
$username$directory[](fg:#212337)$fill[](fg:#212337)[ ](bg:#212337)$status[ ](bg:#212337)$git_branch$git_status$time
$character
"""

add_newline = true

scan_timeout = 50

command_timeout = 5000

[character]
# success_symbol = "[](fg:#50fa7b bold)"
# success_symbol = "[❯](fg:#50fa7b bold)"
success_symbol = "[❯](fg:#37f499)"
# error_symbol = "[](fg:#ff5555 bold)"
# error_symbol = "[❯](fg:#ff5555 bold)"
error_symbol = "[❯](fg:#f16c75)"

[fill]
symbol = " "
disabled = false

[time]
# format = '[](fg:#e0def4 bg:#191724)[](fg:#908caa bg:#e0def4)[](fg:#6e6a86 bg:#908caa)[](fg:#26233a bg:#6e6a86)[ \[$time\] ](fg:#e0def4 bg:#26233a)'
format = '[](fg:#f7c67f bg:#212337)[ \[$time\] ](fg:#f7c67f bg:#212337)'
utc_time_offset = "local"
time_format = "%H:%M:%S"
disabled = false
time_range = "-"

[cmd_duration]
min_time = 1
show_milliseconds = true
format = "[]($style)[[神](fg:#ebfafa)$duration](fg:#ebfafa)"
style = "fg:#ebfafa"

[git_branch]
# format = "[ ](fg:#e0def4 bg:#26233a)[$symbol](fg:#e0def4 bg:#26233a)[$branch](fg:#e0def4 bg:#26233a)[](fg:#26233a bg:#26233a)"
format = "[ ](fg:#f1fc79 bg:#212337)[ ](fg:#f1fc79 bg:#212337)[$branch ](fg:#f1fc79 bg:#212337)"
symbol = " "

[shell]
bash_indicator = "[](fg:#6c7086 bg:#313244)[](fg:#a6adc8 bg:#6c7086)[](fg:#cdd6f4 bg:#a6adc8)[BSH](fg:#313244 bg:#cdd6f4)[](fg:#cdd6f4 bg:#a6adc8)[](fg:#a6adc8 bg:#6c7086)[](fg:#6c7086 bg:#313244)[  ](fg:#cdd6f4 bg:#313244)[](fg:#313244 bg:#6c7086)[](fg:#6c7086 bg:#a6adc8)[](fg:#a6adc8 bg:#cdd6f4)[](fg:#cdd6f4 bg:#1e1e2e)"
zsh_indicator = "[](fg:#6c7086 bg:#313244)[](fg:#a6adc8 bg:#6c7086)[](fg:#cdd6f4 bg:#a6adc8)[ZSH](fg:#313244 bg:#cdd6f4)[](fg:#cdd6f4 bg:#a6adc8)[](fg:#a6adc8 bg:#6c7086)[](fg:#6c7086 bg:#313244)[  ](fg:#cdd6[f4 bg:#313244)[](fg:#313244 bg:#6c7086)[](fg:#6c7086 bg:#a6adc8)[](fg:#a6adc8 bg:#cdd6f4)[](fg:#cdd6f4 bg:#1e1e2e)"
nu_indicator = "[](fg:#6c7086 bg:#313244)[](fg:#a6adc8 bg:#6c7086)[](fg:#cdd6f4 bg:#a6adc8)[NSH](fg:#313244 bg:#cdd6f4)[](fg:#cdd6f4 bg:#a6adc8)[](fg:#a6adc8 bg:#6c7086)[](fg:#6c7086 bg:#313244)[  ](fg:#cdd6f4 bg:#313244)"
# fish_indicator = "[](fg:#eb6f92 bg:#191724)[](fg:#a6adc8 bg:#6c7086)[](fg:#cdd6f4 bg:#a6adc8)[FSH](fg:#191724 bg:#e0def4)[](fg:#cdd6f4 bg:#a6adc8)[](fg:#a6adc8 bg:#6c7086)[](fg:#6c7086 bg:#313244)[  ](fg:#cdd6f4 bg:#313244)[](fg:#313244 bg:#6c7086)[](fg:#6c7086 bg:#a6adc8)[](fg:#a6adc8 bg:#cdd6f4)[](fg:#cdd6f4 bg:#1e1e2e)"
# fish_indicator = "[](fg:#6e6a86 bg:#26233a)[](fg:#908caa bg:#6e6a86)[](fg:#e0def4 bg:#908caa)[FSH](fg:#191724 bg:#e0def4)[](fg:#e0def4 bg:#908caa)[](fg:#908caa bg:#6e6a86)[](fg:#6e6a86 bg:#26233a)[  ](fg:#e0def4 bg:#26233a)[](fg:#26233a bg:#6e6a86)[](fg:#6e6a86 bg:#908caa)[](fg:#908caa bg:#e0def4)[](fg:e0def4 bg:#181724)"
elvish_indicator = "[](fg:#6c7086 bg:#313244)[](fg:#a6adc8 bg:#6c7086)[](fg:#cdd6f4 bg:#a6adc8)[ESH](fg:#313244 bg:#cdd6f4)[](fg:#cdd6f4 bg:#a6adc8)[](fg:#a6adc8 bg:#6c7086)[](fg:#6c7086 bg:#313244)[  ](fg:#cdd6f4 bg:#313244)[](fg:#313244 bg:#6c7086)[](fg:#6c7086 bg:#a6adc8)[](fg:#a6adc8 bg:#cdd6f4)[](fg:#cdd6f4 bg:#1e1e2e)[](fg:#e0def4 bg:#191724"
# xonsh_indicator = "[](fg:#6c7086 bg:#313244)[](fg:#a6adc8 bg:#6c7086)[](fg:#cdd6f4 bg:#a6adc8)[XSH](fg:#313244 bg:#cdd6f4)[](fg:#cdd6f4 bg:#a6adc8)[](fg:#a6adc8 bg:#6c7086)[](fg:#6c7086 bg:#313244)[  ](fg:#cdd6f4 bg:#313244)[](fg:#313244 bg:#6c7086)[](fg:#6c7086 bg:#a6adc8)[](fg:#a6adc8 bg:#cdd6f4)[](fg:#cdd6f4 bg:#1e1e2e)"
unknown_indicator = "[](fg:#fff1cf bg:#6f6565)[???-MODE][](fg:#6f6565)"
style = "fg:#fff1cf bg:#6f6565"
disabled = true

[directory]
format = "[ 󰣇 ](fg:#04d1f9 bg:#212337)[[ ](fg:#04d1f9 bg:#212337)$path ]($style)[$read_only](fg:#04d1f9 bg:#212337)"
#format = "[  ](fg:#89b4fa bg:#212337)[[ ](fg:#04d1f9 bg:#212337)$path ]($style)[$read_only](fg:#04d1f9 bg:#212337)"
# format = "[ _ ](fg:#cdd9f4 bg:#313244)[ ](fg:#cdd6f4 bg:#313244)[$path ]($style)[$read_only](fg:#cdd6f4 bg:#313244)[](fg:#313244 bg:#6c7086)[](fg:#6c7086 bg:#a6adc8)[](fg:#a6adc8 bg:#cdd6f4)[](fg:#cdd6f4 bg:#1e1e2e)"
# style = "fg:#e0def4 bg:#26233a"
style = "fg:#04d1f9 bg:#212337"
truncation_symbol = " "
truncate_to_repo = false
truncation_length = 100
# home_symbol = "  "
home_symbol = "~"
read_only = " "

[git_status]
format = '(fg:#f1fc79 bg:#212337)([\[$modified $untracked\] ](fg:#f1fc79 bg:#212337))'
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}'
behind = '⇣${count}'
modified = '!${count}'
untracked = '?${count}'

[username]
# format = "[](fg:#6e6a86 bg:#191724)[](fg:#908caa bg:#6e6a86)[](fg:#e0def4 bg:#908caa)[ ](fg:#26233a bg:#e0def4 bold)[](fg:#e0def4 bg:#908caa)[](fg:#908caa bg:#6e6a86)[](fg:#6e6a86 bg:#26233a)"
format = '[$user]($style)'
style_user = "fg:#a48cf2 bg:#212337"
style_root = "fg:#f16c75 bg:#212337"
show_always = true
disabled = false

[os]
# format = "[ 󰣇 ](fg:#ebfafa bg:#26233a)"
format = "[  ](fg:#ebfafa bg:#26233a)"
# format = "[  ](fg:#ebfafa bg:#313244)"
disabled = false
[os.symbols]
Arch = " 󰣇 "
Android = "  "
Pop = "  "

[memory_usage]
disabled = false
format = "$ram_pct"

[status]
disabled = false
symbol = "[✘ ](fg:#f16c75 bg:#212337)"
success_symbol = "[✔ ](fg:#37f499 bg:#212337)"
format = "[$symbol$status]($style)"
style = "fg:#cbb6f4 bg:#212337"

[container]
disabled = false
symbol = " 󱁤 "
style = "bold red dimmed"
format = '[$symbol \[$name\]]($style) '
